### ISSUE TITLE
Timestamp Timezone?

### ISSUE THREAD

**Issue by MitchellVincent** [tylerhall/sosumi#19]
I modified the Example a little bit to show the timestamp of the location information. It's odd but the timestamp seems to always be exactly one hour off local time. I had someone out on the west coast try it and he saw the same thing.

Do you know if Apple is using local time, or time from a central server with that? 

I'd be happy to donate some money to you for doing the leg work on all of this - just point me to a PayPal address or link!

**Comment by tylerhall** [comment]
Actually, the timestamp Apple returns is a Unix timestamp. i.e., the number of milliseconds since 1/1/1970. It's PHP that converts that number into a local date and time.

I'd guess the off by an hour problem you're seeing is due to a timezone/configuration error in your PHP config file. Try setting a default timezone at the top of the script using:

date_default_timezone_set('America/Los_Angeles');

You can get a list of supported timezone values here:

http://www.php.net/manual/en/timezones.php

You can also use date_default_timezone_get() to check and see which timezone PHP is currently using if you're curious.

Donations are appreciated but certainly aren't necessary. But, if you're so inclined, you can send via PayPal to tylerhall [at] gmail [dot] com.

**Comment by MitchellVincent** [comment]
I saw it was a Unix timestamp but found the problem.. In C# I was doing this : 

```
        DateTime Fecha = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);

        return Fecha.ToLocalTime().AddMilliseconds(milliseconds)
```

When I should have been doing : 

```
        DateTime Fecha = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);

        return Fecha.AddMilliseconds(milliseconds).ToLocalTime();
```

Bingo.. PayPal incoming!

**Comment by tylerhall** [comment]
Did you write a C# port of Sosumi? Or are you just piping the PHP output into another system? (just curious)

**Comment by MitchellVincent** [comment]
Pure C# but it isn't really a true port. I'm writing something to track mileage on some of my employee's work cars by constantly recording location information to a local database. It's going to be interesting to see how the calculated mileage compares to the odometer mileage. Calculating distance traveled using only long/lat isn't as accurate as measuring at the wheel but I hope to get it close.

You did the legwork by defining the fields and figuring out the server locations. I was in the middle of doing that  when someone sent me a link to your project so you saved me a ton of time!
