### ISSUE TITLE
Does this still work after iCloud launch?

### ISSUE THREAD

**Issue by owlboy** [tylerhall/sosumi#24]
Just wondering if this still works after the iCloud launch. I use PlayNice, and that has been broken for awhile now it seems. Hoping for some info!

**Comment by tylerhall** [comment]
It should - I've been testing against the iCloud beta for a while now.
I can't vouch for PlayNice, since it might not be using the latest
version of Sosumi. But I'll check into Sosumi once the official iCloud
rollout settles down.

On Wed, Oct 12, 2011 at 6:20 PM, Bryan Bortz
reply@reply.github.com
wrote:

**Comment by owlboy** [comment]
Thanks for the info and continued support of sosumi!

**Comment by tylerhall** [comment]
I just confirmed Sosumi is still working. I was able to find the locations of all my iOS and Mac devices.
